### ISSUE TITLE
libsodium is not working? Undefined function?

### ISSUE THREAD

**Issue by ximuh** [jedisct1/libsodium-php#100]
Here is my stackoverflow post: http://stackoverflow.com/questions/40684596/libsodium-for-php-is-not-working

what could be wrong?

**Comment by jedisct1** [comment]
What PHP version are you using?

**Comment by paragonie-scott** [comment]
It's most likely compiled against libsodium 1.0.3 or 1.0.8

**Comment by ximuh** [comment]
I'm using PHP 7.0. One of the versions is 1.0.8 and the libsodium from PECL is 1.0.6.

Here's what I get when I put this:
`<?php
var_dump([
    \Sodium\library_version_major(),
    \Sodium\library_version_minor(),
    \Sodium\version_string()
]);` : array(3) { [0]=> int(9) [1]=> int(1) [2]=> string(5) "1.0.8" } 

Here's what i get when I try to install `pecl install libsodium`: pecl/libsodium is already installed and is the same as the released version 1.0.6

**Comment by ximuh** [comment]
@jedisct1 @paragonie-scott 

I'm using PHP 7.0. One of the versions is 1.0.8 and the libsodium from PECL is 1.0.6.

Here's what I get when I put this:
`<?php
var_dump([
    \Sodium\library_version_major(),
    \Sodium\library_version_minor(),
    \Sodium\version_string()
]);` : array(3) { [0]=> int(9) [1]=> int(1) [2]=> string(5) "1.0.8" } 

Here's what i get when I try to install `pecl install libsodium`: pecl/libsodium is already installed and is the same as the released version 1.0.6

**Comment by paragonie-scott** [comment]
Right. In order for these functions to be available in the PHP extension, the extension must be built against [version 1.0.9+ of the library](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html).

Your OS is providing a stale package, erroneously, instead of doing the correct thing (providing 1.0.11). This is probably the result of an incorrect idea of what "stable" means upstream.

Your best bet: Follow the instructions for compiling from source. https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium#installing-libsodium-source

**Comment by ximuh** [comment]
@paragonie-scott @jedisct1 

So you're talking about the PECL extension that is currently at 1.0.6... you're saying I need to update that to 1.0.9?

**Comment by paragonie-scott** [comment]
No. You currently have:

* Libsodium: 1.0.8
* ext/libsodium: 1.0.6

You need:

* Libsodium: 1.0.9+
* ext/libsodium: 1.0.6

It's not the PECL extension that's out of date. It's the underlying library that's out of date.

**Comment by ximuh** [comment]
Awesome fixed!
