### ISSUE TITLE
Please bring back support for libsodium < 1.0.9

### ISSUE THREAD

**Issue by dzuelke** [jedisct1/libsodium-php#141]
The current Ubuntu LTS (16.04) is at version 1.0.8: https://packages.ubuntu.com/xenial/libsodium18

It'll be useful for fast adoption of the extension, and common use with PHP 7.2, if such slightly older versions are supported.

I realize the code is cleaner, but judging from the commit message for e4d6d281cf197deb0086b592a72f282905ba7ead, it's not absolutely critical to have 1.0.9, just nicer, and I think the trade-off there is worth reverting.

**Comment by jedisct1** [comment]
Version 1.0.9 is already getting old and missing features that have to be reimplemented or worked around. And this will require more and more workarounds for it as new versions of the library get released.

Even Debian ships more recent packages, so 1.0.9 is a reasonable minimum version to support.

Unfortunately, supporting obsolete versions is time consuming. Maintaining code to emulate features available in newer versions is time consuming. Testing them on obsolete operating systems is time consuming.

You're asking me to write and maintain quirks so that an extension I don't use for a language I never use so it can work with an old version of a library on an operating system I don't use.

This is work, it's not something I can do for free, for fun.

If people actually using this environment on a daily basis could contribute up-to-date libsodium packages instead, that would be fantastic.

**Comment by jedisct1** [comment]
It might work with 1.0.8 now.

It compiles, I don't know if it works.

**Comment by dzuelke** [comment]
Finally had a chance to do some testing, seems to work great. Thanks @jedisct1!
