### ISSUE TITLE
[NFR] Ability to utilize crypto_pwhash_argon2id* methods

### ISSUE THREAD

**Issue by moderndeveloperllc** [jedisct1/libsodium-php#143]
This may already be on the map, but it would be great to be able to use the new Argon2id methods with the module.

**Comment by paragonie-scott** [comment]
I'd also like to get this into PHP 7.2 so I can make Halite v4 use Argon2id as well. 👍

**Comment by jedisct1** [comment]
`crypto_pwhash()` already accepts an algorithm identifier.

`crypto_pwhash_str_verify()` will automatically extract the algorithm from the string prefix.

`crypto_pwhash_str()` still uses Argon2i in order to avoid complains from people mixing multiple libsodium versions. This will change in version 1.0.15.

Version 1.0.14 introduces a `crypto_pwhash_str_alg()` function to explicitly choose the algorithm. This can be ported to PHP.

That said, my little pinkie told me that the Argon2 specification may slightly change. Sigh. Again. Yes. Soon. So don't settle on anything yet.

**Comment by jedisct1** [comment]
My recommendation would be to just use the default algorithm (`pwhash_str()` and `pwhash()` with `alg_default()`) whenever possible.

This will always be set to something reasonable according to what the installed library version supports.

When used for key derivation, save the value of `alg_default()` along with the hashed password.

**Comment by jedisct1** [comment]
And [this](https://github.com/ALRBP/Attack-Argon2i) is the reason the specification may change. Since Argon2id also relies on Argon2i, it may be impacted as well.

The Argon2 team was made aware of this, and the implications are not known yet. Having raw code without any details nor paper doesn't help.

**Comment by moderndeveloperllc** [comment]
Thanks for the update. Didn’t know about the possible spec update. I’ll stick with 2i till everything shakes itself out. Can always rehash on login latter!
