### ISSUE TITLE
Build errors PHP 7.0  & 7.1

### ISSUE THREAD

**Issue by Jan-E** [jedisct1/libsodium-php#152]
On Windows the 2.0.6-release does not build anymore. See
http://windows.php.net/downloads/pecl/releases/libsodium/2.0.6/logs/

Inside http://windows.php.net/downloads/pecl/releases/libsodium/2.0.6/logs/php_libsodium-2.0.6-7.1-nts-vc14-x64-logs.zip you can look at the end of make-php_libsodium-2.0.6-7.1-nts-vc14-x64.txt to see the errors.

**Comment by Jan-E** [comment]
@jedisct1 This commit is the guilty one:
https://github.com/jedisct1/libsodium-php/commit/5407c118eee864c57c5de6f2772c65cbc7429885

**Comment by jedisct1** [comment]
I still use PHP 7.0, so it probably doesn't compile either on PHP 7.2 under the same environment.

It's probably unrelated to the PHP version, but rather to the libsodium version, since it errors out on functions that were introduced in libsodium 1.0.14.

I need to add a couple `#ifdef` for old libsodium versions.

Thanks for the quick report!

**Comment by Jan-E** [comment]
With libsodium 1.0.13 and the bundled PHP7.2-sources it does not fail with PHP 7.2.0RC3. See
https://phpdev.toolsforresearch.com/php-7.2.0RC3-nts-Win32-VC15-x64.htm
for a phpinfo() dump

**Comment by jedisct1** [comment]
The source code bundled with PHP 7.2 is running way behind the PECL extension.

Indentation is not the same, some 3rd party code was merged there and cannot be merged back to the PECL extension because the license is not the same, so keeping both in sync is getting more and more difficult.

And with PHP 7.2 being currently in RC stage, I prefer to avoid touching it too much, and focus on the PECL extension instead.

**Comment by jedisct1** [comment]
Anyway, c50678bd8c7a24f85a0290aec75c61c678a0d70a should fix it.

Thanks again for your report, Jan!

**Comment by Jan-E** [comment]
BTW: Building is OK with 2.0.7 and libsodium 1.0.13
Maybe you should ping @weltling to update libsodium on windows.php.net to version 1.0.14.

**Comment by jedisct1** [comment]
Ping @weltling :)

**Comment by weltling** [comment]
@Jan-E, @jedisct1 hanks for the ping. I've just checked and there is already libsodium-1.0.13 on the build host there. But for 7.2 snapshots, RC2 is used. 7.2.0RC3 is not yet released, so it's not upgraded there. I'll be watching this to upgrade 7.2 base after it's released and the libsodium libs. Lets see :)

Thanks.

**Comment by Jan-E** [comment]
@weltling: the new functions in the PECL extension rely on libsodium 1.0.14 (not 1.0.13).

**Comment by weltling** [comment]
@Jan-E ah, that explains it. BTW the PECL changelog tells 1.0.9.

Thanks.

**Comment by weltling** [comment]
@Jan-E btw @jedisct1 added ifdefs into the extension, so latest shouldn't fail. Nevertheless worth upgrading, will pull new libs tomorrow.
Thanks.

**Comment by Jan-E** [comment]
The ifdef's do their work OK:
http://windows.php.net/downloads/pecl/releases/libsodium/2.0.7/
