### ISSUE TITLE
Use of undefined constant SODIUM_LIBRARY_MAJOR_VERSION - assumed 'SODIUM_LIBRARY_MAJOR_VERSION

### ISSUE THREAD

**Issue by eaponiente** [jedisct1/libsodium-php#184]
PHP: 7.1
Ubuntu: 14.04

followed all the instructions in the website and last part was put `sodium.so` in my 
`/etc/php/fpm/php.ini`.

now to test it out, I tried the ff code in `php artisan tinker`(ran in command line) inside one of my laravel projects

```
var_dump([
    SODIUM_LIBRARY_MAJOR_VERSION,
    SODIUM_LIBRARY_MINOR_VERSION,
    SODIUM_LIBRARY_VERSION
]);
```
and got this results 
```
array(2) {
  [0] =>
  int(9)
  [1] =>
  int(1)
  [2] =>
  string(6) "1.0.14"
}
```

Now, when I tried the code on my browser.

I am getting this error `Use of undefined constant SODIUM_LIBRARY_MAJOR_VERSION - assumed 'SODIUM_LIBRARY_MAJOR_VERSION`

**Comment by eaponiente** [comment]
wrong repo 💯

**Comment by gnicol-bzh** [comment]
_Just because I had this problem today on Windows, and other people may come here for the same reason..._

I solved this issue by installing the latest version compatible with my version of PHP, the [php_libsodium-2.0.15-7.0-ts-vc14-x64](https://windows.php.net/downloads/pecl/releases/libsodium/2.0.15/)

```
Windows 10 x64
WAMP 3.1.0 64bit
PHP 7.0.24 (and for some reasons, no possibility to update PHP)
```
