### ISSUE TITLE
sodium_crypto_pwhash_str: Any way to specify the algorithm to use (argon2i/argon2id)?

### ISSUE THREAD

**Issue by chalasr** [jedisct1/libsodium-php#194]
Using the pecl in version 2.0.20, it appears that `sodium_crypto_pwhash_str` uses `argon2id` as algorithm. Is there a way to make it use `argon2i` instead?

I'm in charge of the `symfony/security` package (part of the Symfony PHP framework) which provides an Argon2-based password hasher. 
The hasher relies on the `password_hash()` PHP function if one of the `PASSWORD_ARGON2*` constants is available, and let you choose which variant to use (argon2i or argon2id).
But, if the chosen variant is not available as `PASSWORD_` constant, it checks for libsodium to be available and, if it is, relies on it using `sodium_crypto_pwhash_str`. 
Ideally, we would like to be able to choose the argon2 variant to use when relying on the extension, as well as we are able to do it using the `password_hash` argon2 integration of PHP.

If specifying the algorithm is not possible, could you please tell me the version at which `sodium_crypto_pwhash_str` started to use `argon2id`?

Depending on your answer, we might stop allowing to choose the variant, and just take the "best" of the two algorithms depending on the current php/libsodium installation.

Thank you.

**Comment by jedisct1** [comment]
`sodium_crypto_pwhash_str()` uses the best algorithm available in the currently installed version of libsodium for the current platform.

It can be Argon2i, Argon2id, or something else depending on the platform (Argon2 is currently not a good fit for constrained environments and WebAssembly). You shouldn't assume that it is a specific algorithm.

The guarantee is that `sodium_crypto_pwhash_str_verify()` will always be able to verify hash strings made by the current and previous libsodium versions, no matter what algorithm was used.

So that the default algorithm and parameters can be updated without breaking compatibility.

The default algorithm was changed from Argon2i to Argon2id in libsodium 1.0.15. It may change again soon, at least for some platforms.

**Comment by chalasr** [comment]
Makes sense. Thank you for the quick reply
