### ISSUE TITLE
Fatal error with ZSTR_TRUNCATE

### ISSUE THREAD

**Issue by Cyansilver** [jedisct1/libsodium-php#197]
Hi,

I'm facing a fatal error when call **\Sodium\hex2bin**

The message is:

> PHP Warning:  Uncaught exception 'ErrorException' with message 'arithmetic overflow'
> PHP Fatal error:  ZSTR_TRUNCATE() truncating beyond maximum buffer size 

It only happens on a server and not in my laptop (MacOS) but I run it in a docker container for both server and my laptop 

The versions I use:
PHP: 5.6
libsodium: 1.0.6
pecl: libsodium-1.0.6

Not sure what causes it?

**Comment by jedisct1** [comment]
PHP 5.6 has reached end of life, libsodium 1.0.6 is unsupported, and I barely remember what version 1.0.6 of the PECL extension looked like since it's so old as well.

Since you didn't provide any test case, I can't check if this is still happening with current versions.
But you should really update that server no matter what, since the software you are using is not only old, but it won't receive any updates any more, including for security issues.
