### ISSUE TITLE
Problems to decrypt

### ISSUE THREAD

**Issue by reynaldmorel** [jedisct1/libsodium-php#228]
Hello,

I moved some encrypted files to another server so another tree. Since this change, I can't decrypt the files anymore.

I need help.

Thanks a lot.

Sincerely

**Comment by reynaldmorel** [comment]
Hello,

I want to reopen this issue because the problem is not resolved.

**Comment by jedisct1** [comment]
Hello,

I'm sorry to hear that you're having trouble decrypting your files. In order to assist you better, I would need more information about the encryption method you used, the file format of your encrypted files, and the steps you followed to move the files to another server.

Here are a few general suggestions that might be helpful:

- Ensure that you have the correct decryption key or passphrase for your files. If you don't have the correct key or passphrase, you won't be able to decrypt the files.
- Check to make sure that the encryption software you used to encrypt the files is installed on the new server. If it is not, you will need to install it before attempting to decrypt the files.
- If the file format of your encrypted files has changed during the move, you may need to convert the files back to their original format before attempting to decrypt them.
- If you moved the files using a different file transfer method than you used to encrypt them, the files may have become corrupted during the transfer. In this case, you may need to move the files again using the same file transfer method you used originally.
- If you have a backup of the encrypted files, you can try restoring them to the original location and see if you can decrypt them successfully.

I hope these suggestions are helpful. If you provide me with more details about your specific situation, I may be able to offer more specific advice.
