### ISSUE TITLE
Automatically append nonce / IV to ciphertext

### ISSUE THREAD

**Issue by leonklingele** [jedisct1/libsodium-php#33]
From readme:
```php
$nonce = Sodium::randombytes_buf(Sodium::CRYPTO_SECRETBOX_NONCEBYTES);
$key = [a binary string that must be CRYPTO_SECRETBOX_KEYBYTES long];
$ciphertext = Sodium::crypto_secretbox('test', $nonce, $key);
$plaintext = Sodium::crypto_secretbox_open($ciphertext, $nonce, $key);
```
Isn't it the purpose of a library like libsodium to make a programmer's life as easy as possible?
A high level programmer (especially when dealing with crypto stuff) should avoid using nonces at all costs (i.e. pre-/appending them to the ciphertext and later substringing them out).
As the nonce is public, it can automatically be appended to the ciphertext.

There should be a wrapper function (e.g. `Sodium::crypto_secretbox_auto`) which accepts only `DATA_TO_ENCRYPT` and a `KEY`.
It should return the ciphertext including the nonce.

`Sodium::crypto_secretbox_open_auto` on the other hand only accepts `DATA_TO_DECRYPT` (which has the nonce in it) and the `KEY`.
It should extract the nonce, then call and return `Sodium::crypto_secretbox_open`

__`Sodium::crypto_secretbox` was only used as an example. There should be wrapper functions for all functions which accept a nonce / IV / ..__

**Comment by leonklingele** [comment]
Too late :sleepy:. Seems to be related to #31

**Comment by jedisct1** [comment]
Nonces have to be unique for each message encrypted using a given key, but they don't have to be unpredictable.

In fact, most protocols do not use random nonces at all after the first packet, hence don't need to transmit the nonce any more.

Using counters or hashing the previous nonce mitigates reordering and replay attacks. Using random nonces for each message would make these protocols weaker.

When doing file encryption, the nonce can also extend the internal counter in order to represent an offset of a block counter.

Other schemes include having the client contribute half of the nonce, and the server contribute the other half, in order to verify that a received response matches the initial question.

**Comment by leonklingele** [comment]
I understand. So you say one should to use a counter as nonce, starting at 24 bytes × 0x0, then increment each time we need a new nonce? Where to store this counter?

Isn't it secure enough to use (pseudo)random bytes as a nonce? If not, why?
It's so incredibly unlikely to generate a nonce twice if nonce length is 192 bits.
(Even if the nonce would be 96 bits long (we need a 192 bit nonce!) we could generate way over 1,000,000,000,000 nonces before the probability to generate a new nonce – which has already been generated before – reaches ~0.00001.

**Comment by jedisct1** [comment]
Hi,

You are absolutely correct; 192 bit nonces are long enough that the probability of having a collision when choosing them randomly is negligible.

Choosing them randomly is thus totally fine, but my point is that there is a reason why the API gives the developer the ability to specify the nonce.

Most protocols use predictable nonces. Typically, the client sequentially uses 1, 3, 5... as a nonce for each packet, and the server uses 2, 4, 6 ...
Or both the client and the server randomly pick an initial nonce, and increment it after each packet.

The nonce doesn't have to be transmitted along with the data any more. Because only one specific nonce is expected for a given packet, attempts to remove or replay messages are likely to fail.

If a server sends data to a client using nothing but random nonces, the client has to accept any nonce. If an attacker sends a previous packet, there will be no way for the client to detect that this packet shouldn't be there. It used to be valid, sending it one more time doesn't make it invalid, as the MAC still verifies.

The same thing applies if packets are being reordered.

If packets are removed from the stream, this won't be detected either. Having a random nonce for each message makes the messages completely independant. They can be duplicated, removed or reordered.

Now if the 3rd packet received by the client has to be encrypted using a key and nonce `5`, or `civ + 2`, a previous packet cannot be replayed any more, as it will have a different nonce.

Different schemes exists. For example, in dnscrypt and dnscurve, the client sends a query where half of the nonce is randomly chosen, and the other half is all zeros. It only transmits its half to the server. The server randomly chose the other half for its response, encrypts the response using `(client half || server half)` and only transmits its half. Once again, this prevents replay attacks, as for a given question, only one specific nonce (known by the client) can be used to get the response to verify.

**Comment by leonklingele** [comment]
Thank you for clarifying.

Back to my original question: Isn't it a good idea to provide a new function
`Sodium::crypto_secretbox_auto` which does exactly the same thing as
`Sodium::crypto_secretbox`, but automatically generates and appends the nonce to the ciphertext?

Also see this function which only accepts said two parameters (and doing the IV / nonce stuff behind the scenes): https://github.com/defuse/php-encryption/blob/b87737b2eec06b13f025cabea847338fa203d1b4/example.php#L15
This is how it should work for libsodium.

**Comment by paragonie-scott** [comment]
I think this was mentioned before on the mailing list, but this specific use case makes more sense in a higher-level abstraction than in libsodium proper.

I built a toy implementation here, for example: https://github.com/paragonie/halite_cookie

I think a more solid implementation would `crypto_stream_xor()`, prepend the nonce, then `crypto_auth()`. And then for decryption, grab the nonce (`mb_substr()` in 8but mode), `crypto_auth_verify()` and `crypto_stream_xor()` to decrypt.

If there's any interest, I'll probably create a non-toy implementation of a higher level library (I think I'll stick with the name Halite though. They're sodium chloride crystals.)

**Comment by paragonie-scott** [comment]
@leonklingele https://paragonie.com/book/pecl-libsodium/read/09-recipes.md#encrypted-cookies Does something like this solve your immediate needs?

**Comment by paragonie-scott** [comment]
Update: https://github.com/paragonie/halite/blob/ee5e92ee65dfebf26b7d8c559921ce2a5d4cf76c/src/Symmetric/Crypto.php#L133-L168

While I still would not recommend using Halite in production yet (it's experimental and being developed, bugs might happen), this might in the end satisfy these sorts of requests for PHP developers.

**Comment by paragonie-scott** [comment]
@leonklingele Halite is stable if you'd like to use a higher-level API to automatically append/prepend the nonce to the ciphertext.

This will also be a feature in the pluggable crypto API that I intend to write for PHP 7.1: https://github.com/paragonie/pco_prototype

So, yeah, you've got options :)

**Comment by jedisct1** [comment]
@tomekit https://github.com/jedisct1/libsodium-php#encrypt-a-file-using-a-secret-key

https://doc.libsodium.org/secret-key_cryptography/secretstream

**Comment by tomekit** [comment]
Thanks @jedisct1, I believe I've been there at least once. I believe there is a need for wrapper around this, as honestly I find prepending/appending nonce myself more convenient then using streaming API for non-streamed operation, but that's my personal taste.
I am thinking of something like: `crypto_secretbox_easy` but with `nonce` handling also included.
This is possibly out of scope for `libsodium-php` or maybe even `libsodium` itself and I am sure there are plenty wrappers on Github, I was simply dreaming to have it built-in in the library.
