### ISSUE TITLE
Fatal error when decrypting truncated ciphertext with crypto_secretbox_open

### ISSUE THREAD

**Issue by notr1ch** [jedisct1/libsodium-php#45]
Hello,
I receive a "PHP Fatal error:  crypto_secretbox_open(): short ciphertext" when decrypting truncated ciphertext.

I don't think this should be a fatal error, it should be treated the same as a failed decryption, allowing the application to handle it. For example, I send a blob of ciphertext to a client and they truncate it (for whatever reason) when they send it back to my application and I want to be able to handle it the same as if the ciphertext was modified and there was a decryption error. This is a common use case for encrypted cookies or other authentication tokens.

The more important question is how do I know what the minimum accepted ciphertext is which won't cause a fatal error? There doesn't appear to be a CRYPTO_SECRETBOX_MACBYTES constant which the original libsodum documentation implies is the minimum length.

**Comment by leonklingele** [comment]
Also see #35 and #37

**Comment by jedisct1** [comment]
Hi Richard,

The reasoning behind this was that in the context of a protocol, having short ciphertexts cannot possibly happen without a bug in the logic or in the its implementation.

But you are absolutely correct, having to check the length against `CRYPTO_SECRETBOX_MACBYTES` shouldn't be required; the error path for short messages is usually the same as for messages whose MAC doesn't verify.

This has been fixed in 1b51fd62aa257c9fd8a514e85805db882dc3e2e8 

Also thanks for the heads up about `CRYPTO_SECRETBOX_MACBYTES` not being defined. This has been fixed as well.
