### ISSUE TITLE
Automatically append padding?

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium-php#71]
Similar to https://github.com/jedisct1/libsodium-php/issues/33 why not automatically append padding?
Currently the dev still has to do it by himself creating potential vulnerabilities if it is wrong.

Is there even a special function of libsodium only for appending padding or something like this?

**Comment by jedisct1** [comment]
Hi Rugk,

Can you clarify why you need padding and what potential vulnerabilities you are referring to?

libsodium ciphers are all stream ciphers with the exception of AES, which is only available in CTR mode, which doesn't require padding. Padding oracle attacks are not relevant to the available constructions.

**Comment by rugk** [comment]
I think just to change the size of the encrypted data a bit so it is not so easy for an attacker to guess the content or get out how large the message was.

Obviously this only makes sense for small amounts of data like messages for mobile messengers. So e.g. this is [used by Threema](https://threema.ch/press-files/2_documentation/cryptography_whitepaper.pdf#page9) (page 9) (which uses NaCl):
> ##### Padding
In order to thwart attempts to guess the content of short messages by looking at the amount of data, Threema adds a random amount of PKCS#7 padding to each message before end-to-end encryption.

You can see it's open-source implementations (for their Gateway service) here: [PHP](https://github.com/rugk/threema-msgapi-sdk-php/blob/c53f79ffd11b7d18931934c8ee35ce6d278bbd62/source/Threema/MsgApi/Tools/CryptTool.php#L109-L113), [Python](https://github.com/lgrahl/threema-msgapi-sdk-python/blob/master/threema/gateway/e2e.py#L47-L51), [Java](https://github.com/threema-ch/threema-msgapi-sdk-java/blob/3387aaaba0c572d9575c22d5a0e7f65a26b7424c/source/src/main/java/ch/threema/apitool/CryptTool.java#L122-L141).*

So the only purpose of this is to hide the size of a message. So I have to take back the "potentially vulnerability" - this is more of an "additional feature". :smiley: 

So well... obviously this is something which only makes sense for a small amount of data, so possibly a general implementation in this library dos not make much sense.
Therefore I am closing this issue. If anyone feels implementing this in some way would make sense this issue can of course be reopened.

\* BTW do not freak out because of these pseudo-random-number generators there. (I also thought what-the-hell were I saw it first). [I've already asked on Stackexchange](https://crypto.stackexchange.com/questions/31436/is-pkcs7-padding-generated-with-a-pseudo-random-number-generator-okay) whether this is okay.

**Comment by jedisct1** [comment]
This is very specific to the protocol being implemented. If the messages already include a length, additional bits can be appended without any other consideration. They will naturally be ignored after decryption. The same thing applies if messages have a delimiter, such as 0-terminated strings, DNS qnames, JSON data and other common serialization formats.
If the message doesn't include any hints about its length, padding schemes such as PKCS7 or IEC 7816-4 can be an option. Naive implementations are fine with the libsodium constructions, that all use encrypt-then-mac.

Padding is not only useful with very short messages. You may want to use it to hide the nature of a document, or make it impossible to match a document whose size is known.
PKCS7 only allows up to 255 bytes of padding, which is not enough for some protocols. For example, dnscrypt use padding to require questions to be at least as large as responses, in order to mitigate amplification attacks. IEC 7816-4 doesn't have this limitation, but requires all the bytes to be checked even when the construction doesn't require it, so there is a performance hit.

There is no such thing as a one-size-fits-all padding scheme. It is really specific to a given protocol.
So, it's probably better to keep the library focused on cryptographic primitives instead of adding functions to design protocols, that would be either insufficient or suboptimal.

**Comment by rugk** [comment]
Thanks for the detailed explanation :+1:  and as I already said I also think now that this is not a thing which should be added to this library.
But it is good that there is this issue so that people know (when they look for it) when and why to use padding.

BTW: Is there anything in the doc about this padding thing? I mean people should be aware that using padding (in the way they need it) might be useful.

**Comment by paragonie-scott** [comment]
Padding isn't a usual concern, and if it is something you need to deal with, it's usually because you have a specific requirement out of the scope of a general-purpose cryptography library. I'm not sure if we should address this in the docs, but [they're on Github](https://github.com/paragonie/pecl-libsodium-doc).

**Comment by rugk** [comment]
Do it or do it not. It was just an idea.

**Comment by jedisct1** [comment]
Quoting my answer on SX:

If the intent of the padding is to make a passive attacker learn only a range instead of the exact message length, do not use `real_len + rand(max_padlen)`. It is more efficient to make the length of the padded message a multiple of a given block size instead.

If your protocol has enough latitude to allow large variations of the padding length, you can use a randomized length, but watch out for replay attacks. If for a given question, the same response is always sent, the question can be sent multiple times, so that the actual response length can be eventually inferred. In order to mitigate this, the padding length should always be the same for a given question. A simple PRF can be used to achieve this.

**Comment by jedisct1** [comment]
To summarize, even if there are many ways to achieve this, here are my recommendations for padding with `crypto_box`:
- Make sure the message includes its own size
- Pad with a constant. Always padding with `0` is fine.
- Padding length: `((message_len + BLOCKSIZE - 1) & ~(BLOCKSIZE - 1)) - message_len`
- Don't bother verifying the padding. It's included in the authentication tag.

**Comment by paragonie-scott** [comment]
> Always padding with `0` is fine.

Unless your plaintext is raw binary and might end with a that byte. PKCS7 padding would be better in these edge cases for block sizes < 256, but I don't know of any standards that work well with `BLOCKSIZE >= 256`.

A compromise might be: The last (N = 4) bytes specify the number of padding bytes, which can all be `0`.

**Comment by jedisct1** [comment]
1) Make sure the message includes its own size.

If it's raw binary, prepend the size. Keep things simple.

**Comment by jedisct1** [comment]
> A compromise might be: The last (N = 4) bytes specify the number of padding bytes, which can all be 0.

That works, too. `N` can be less than 4, according to your needs.
In any case, you don't need to parse the actual padding bytes, and what they actually are is pointless.

This works with AE, but don't do this in other contexts.

**Comment by rugk** [comment]
Very thanks for these comments. Just pinging @threema so they know your recommendations. (Although I've obviously already made them aware of this issue)

I'll let you know their response should they reply me via mail.
